allowBuilds:
  'esbuild@0.28.1 || 0.28.2': true
  'workerd@1.20260907.1 || 1.20260908.1': true
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@14.3.1'
  - '@astrojs/markdown-satteri@0.4.1'
  - astro@7.3.2
  - miniflare@5.20260908.0-alpha
  - wrangler@4.130.0
overrides:
  sharp: 0.35.4
