packages:
  - apps/*

allowBuilds:
  'esbuild@0.28.1 || 0.28.2': true

minimumReleaseAgeExclude:
  - '@astrojs/vercel@11.0.10'
  - '@astrojs/markdown-satteri@0.4.1'
  - astro@7.3.2
  - turbo@2.10.12

overrides:
  path-to-regexp: 6.3.0
  sharp: 0.35.4
